-- MySQL Script generated by MySQL Workbench
-- Sat May 14 21:47:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pgs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pgs` DEFAULT CHARACTER SET utf8 ;
USE `pgs` ;

-- -----------------------------------------------------
-- Table `pgs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `email` LONGTEXT NOT NULL COMMENT 'email of the user',
  `password` LONGTEXT NOT NULL COMMENT 'password of the user',
  `login` LONGTEXT NOT NULL COMMENT 'login or username to make login to the system',
  `phone` DOUBLE NOT NULL COMMENT 'Phone number of the user',
  `address` LONGTEXT NOT NULL COMMENT 'Address of the user',
  `token` LONGTEXT NULL DEFAULT NULL COMMENT 'The token of the device for notification sending',
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'The users of the system. It may include pet owners and steticists and pet grooming shop owners or admins';


-- -----------------------------------------------------
-- Table `pgs`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`clients` (
  `id_client` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `client_number` INT(11) NOT NULL COMMENT 'Client ID Number',
  `document_type` TINYINT(1) NOT NULL COMMENT 'Type of Document Number',
  `client_name` LONGTEXT NOT NULL COMMENT 'Name of the Client',
  `last_visited` TIMESTAMP NOT NULL COMMENT 'Last time when the client came',
  `discount` INT(11) NOT NULL COMMENT 'Special disccount fot this client',
  `pending_payment` INT(11) NOT NULL COMMENT 'Amount pending for payment',
  `id_user` INT(11) NOT NULL COMMENT 'The user registry for this client',
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `client_number_UNIQUE` (`client_number` ASC) VISIBLE,
  INDEX `fk_clients_users_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_clients_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `pgs`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Clients of the Pet Grooming Shop';


-- -----------------------------------------------------
-- Table `pgs`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`statuses` (
  `id_status` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `description` LONGTEXT NOT NULL COMMENT 'Description of the status',
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Statuses of the visits of the pets';


-- -----------------------------------------------------
-- Table `pgs`.`fur_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`fur_statuses` (
  `id_fur_status` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `description` LONGTEXT NOT NULL COMMENT 'Description of the fur status',
  `factor` DOUBLE NOT NULL COMMENT 'Factor to calculate the final amount of the service',
  PRIMARY KEY (`id_fur_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Fur statuses for the pets';


-- -----------------------------------------------------
-- Table `pgs`.`pet_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`pet_types` (
  `id_pet_type` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID for registry',
  `name` LONGTEXT NOT NULL COMMENT 'Name of the Pet Type',
  PRIMARY KEY (`id_pet_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Types of pets in the system';


-- -----------------------------------------------------
-- Table `pgs`.`pet_breeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`pet_breeds` (
  `id_pet_breed` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID for this regisrty',
  `name` LONGTEXT NOT NULL COMMENT 'Name of the Pet Breed',
  `id_pet_type` INT(11) NOT NULL COMMENT 'Type of Pet for this Pet Breed',
  PRIMARY KEY (`id_pet_breed`),
  INDEX `fk_pet_types_id_pet_types` (`id_pet_type` ASC) VISIBLE,
  CONSTRAINT `fk_pet_types_id_pet_types`
    FOREIGN KEY (`id_pet_type`)
    REFERENCES `pgs`.`pet_types` (`id_pet_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Breeds of Pets in the system';


-- -----------------------------------------------------
-- Table `pgs`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`pets` (
  `id_pet` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `name` LONGTEXT NOT NULL COMMENT 'Name of the pet',
  `birth_date` DATE NOT NULL COMMENT 'Dat for birth of the pet',
  `gender` TINYINT(1) NOT NULL COMMENT 'Gender of the pet',
  `is_sterilized` TINYINT(1) NOT NULL COMMENT 'Is the pet already sterilized',
  `is_vaccined` TINYINT(1) NOT NULL,
  `weight` DOUBLE NOT NULL COMMENT 'Weight in KG of the pet',
  `photo` LONGTEXT NULL DEFAULT NULL COMMENT 'Binary of the photo of the pet',
  `additional_observations` LONGTEXT NULL DEFAULT NULL COMMENT 'Some important things to know about the pet',
  `last_visited` TIMESTAMP NOT NULL COMMENT 'Las time when the pet came',
  `id_user` INT(11) NOT NULL COMMENT 'Owner of the pet',
  `id_pet_breed` INT(11) NOT NULL COMMENT 'Breed of the pet',
  `id_fur_status` INT(11) NOT NULL COMMENT 'Current status of the fur of the pet',
  PRIMARY KEY (`id_pet`),
  INDEX `fk_users_id_user` (`id_user` ASC) VISIBLE,
  INDEX `fk_pet_breeds_id_pet_breed` (`id_pet_breed` ASC) VISIBLE,
  INDEX `fk_fur_statuses_id_fur_status` (`id_fur_status` ASC) VISIBLE,
  CONSTRAINT `fk_fur_statuses_id_fur_status`
    FOREIGN KEY (`id_fur_status`)
    REFERENCES `pgs`.`fur_statuses` (`id_fur_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_breeds_id_pet_breed`
    FOREIGN KEY (`id_pet_breed`)
    REFERENCES `pgs`.`pet_breeds` (`id_pet_breed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `pgs`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Pets';


-- -----------------------------------------------------
-- Table `pgs`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`services` (
  `id_service` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `name` LONGTEXT NOT NULL COMMENT 'Name of the service',
  `average_time` TIME NOT NULL COMMENT 'Average time of completion for this service',
  `base_amount` INT(11) NOT NULL COMMENT 'base amount to charge the owner of the pet',
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Services offered by the pet grooming store';


-- -----------------------------------------------------
-- Table `pgs`.`visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`visits` (
  `id_visit` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID for this registry',
  `visit_date` TIMESTAMP NOT NULL COMMENT 'The date when the pet visited us',
  `initial_description` LONGTEXT NOT NULL COMMENT 'Some notes written by the steticist when the pet got in',
  `final_description` LONGTEXT NOT NULL COMMENT 'Some notes written by the steticist when the pet got out',
  `real_time_used` TIME NULL COMMENT 'The amount of time in minutes effectively used for attend the visit',
  `total_amount` INT(11) NOT NULL COMMENT 'Total amount in currency charged to the owner for the visit',
  `uuid` LONGTEXT NOT NULL COMMENT 'The UUID that will be printed in QR',
  `id_service` INT(11) NOT NULL COMMENT 'The service made in this visit',
  `id_status` INT(11) NOT NULL COMMENT 'The current status of the service',
  `id_user` INT(11) NOT NULL COMMENT 'The steticist that is making the service to the pet',
  `id_pet` INT(11) NOT NULL COMMENT 'The pet',
  PRIMARY KEY (`id_visit`),
  INDEX `fk_pets_id_pet_1` (`id_pet` ASC) VISIBLE,
  INDEX `fk_services_id_service` (`id_service` ASC) VISIBLE,
  INDEX `fk_status_id_status` (`id_status` ASC) VISIBLE,
  INDEX `fk_steticist_id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_status_id_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `pgs`.`statuses` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_steticist_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `pgs`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pets_id_pet_1`
    FOREIGN KEY (`id_pet`)
    REFERENCES `pgs`.`pets` (`id_pet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_services_id_service`
    FOREIGN KEY (`id_service`)
    REFERENCES `pgs`.`services` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'The visits of the pets and owner in the pet grooming store';


-- -----------------------------------------------------
-- Table `pgs`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`promotions` (
  `id_promotion` INT(11) NOT NULL COMMENT 'Id for this registry',
  `id_visit` INT(11) NOT NULL COMMENT 'The visit to make promotion',
  `factor` DOUBLE NOT NULL COMMENT 'The factor of the promotion in percent',
  PRIMARY KEY (`id_promotion`),
  INDEX `fk_visits_id_visit` (`id_visit` ASC) VISIBLE,
  CONSTRAINT `fk_visits_id_visit`
    FOREIGN KEY (`id_visit`)
    REFERENCES `pgs`.`visits` (`id_visit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Promotions for the visitors';


-- -----------------------------------------------------
-- Table `pgs`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`roles` (
  `id_role` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `name` LONGTEXT NOT NULL COMMENT 'Name of the role',
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Roles of the users in the system';


-- -----------------------------------------------------
-- Table `pgs`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`user_roles` (
  `id_user_role` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id for this registry',
  `id_user` INT(11) NOT NULL,
  `id_role` INT(11) NOT NULL,
  PRIMARY KEY (`id_user_role`),
  INDEX `fk_user_roles_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_user_roles_roles1_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `pgs`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `pgs`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Roles mapping for users';


-- -----------------------------------------------------
-- Table `pgs`.`satisfaction_assessments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pgs`.`satisfaction_assessments` (
  `id_satisfaction_assessment` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'PK for the satisfaction assessment',
  `score` TINYINT(1) NOT NULL COMMENT 'Score of the satisfaction assessment',
  `id_visit` INT(11) NOT NULL COMMENT 'The visit related to this satisfaction assessment',
  PRIMARY KEY (`id_satisfaction_assessment`),
  INDEX `fk_visits_id_visit_1` (`id_visit` ASC) VISIBLE,
  CONSTRAINT `fk_visits_id_visit_1`
    FOREIGN KEY (`id_visit`)
    REFERENCES `pgs`.`visits` (`id_visit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Satisfactions Assessments for the visits';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pgs`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`users` (`id_user`, `email`, `password`, `login`, `phone`, `address`, `token`) VALUES (DEFAULT, 'camilodiaz369@gmail.com', 'Password123.', 'camilodiaz369', 3178241317, 'Calle Falsa 123 # 45 - 67', NULL);
INSERT INTO `pgs`.`users` (`id_user`, `email`, `password`, `login`, `phone`, `address`, `token`) VALUES (DEFAULT, 'dpvillalobosm@gmail.com', 'Diana312456.', 'dpvillalobosm', 3224640065, 'Carrera 89 # 12 - 34', NULL);
INSERT INTO `pgs`.`users` (`id_user`, `email`, `password`, `login`, `phone`, `address`, `token`) VALUES (DEFAULT, 'pepito.perez@gmail.com', 'Contra12345.', 'pepitop', 3105555555, 'Calle 56 # 78 - 90', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`clients`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`clients` (`id_client`, `client_number`, `document_type`, `client_name`, `last_visited`, `discount`, `pending_payment`, `id_user`) VALUES (DEFAULT, 1022123456, 1, 'Pepito Pérez', CURRENT_TIMESTAMP(), 0, 0, 3);
INSERT INTO `pgs`.`clients` (`id_client`, `client_number`, `document_type`, `client_name`, `last_visited`, `discount`, `pending_payment`, `id_user`) VALUES (DEFAULT, 1032442214, 1, 'Camilo Andrés Díaz Serrano', CURRENT_TIMESTAMP(), 0, 0, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`statuses` (`id_status`, `description`) VALUES (DEFAULT, 'Agendada');
INSERT INTO `pgs`.`statuses` (`id_status`, `description`) VALUES (DEFAULT, 'En sala de espera/Ingreso');
INSERT INTO `pgs`.`statuses` (`id_status`, `description`) VALUES (DEFAULT, 'En servicio');
INSERT INTO `pgs`.`statuses` (`id_status`, `description`) VALUES (DEFAULT, 'En sala de espera/egreso');
INSERT INTO `pgs`.`statuses` (`id_status`, `description`) VALUES (DEFAULT, 'Entregado');
INSERT INTO `pgs`.`statuses` (`id_status`, `description`) VALUES (DEFAULT, 'Perdido');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`fur_statuses`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`fur_statuses` (`id_fur_status`, `description`, `factor`) VALUES (DEFAULT, 'Pelaje corto', 1);
INSERT INTO `pgs`.`fur_statuses` (`id_fur_status`, `description`, `factor`) VALUES (DEFAULT, 'Pelaje corto/medio', 1.25);
INSERT INTO `pgs`.`fur_statuses` (`id_fur_status`, `description`, `factor`) VALUES (DEFAULT, 'Pelaje medio', 1.5);
INSERT INTO `pgs`.`fur_statuses` (`id_fur_status`, `description`, `factor`) VALUES (DEFAULT, 'Pelaje medio/largo', 1.75);
INSERT INTO `pgs`.`fur_statuses` (`id_fur_status`, `description`, `factor`) VALUES (DEFAULT, 'Pelaje largo', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`pet_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`pet_types` (`id_pet_type`, `name`) VALUES (DEFAULT, 'Perro');
INSERT INTO `pgs`.`pet_types` (`id_pet_type`, `name`) VALUES (DEFAULT, 'Gato');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`pet_breeds`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`pet_breeds` (`id_pet_breed`, `name`, `id_pet_type`) VALUES (DEFAULT, 'Pequeño', 1);
INSERT INTO `pgs`.`pet_breeds` (`id_pet_breed`, `name`, `id_pet_type`) VALUES (DEFAULT, 'Mediano', 1);
INSERT INTO `pgs`.`pet_breeds` (`id_pet_breed`, `name`, `id_pet_type`) VALUES (DEFAULT, 'Grande', 1);
INSERT INTO `pgs`.`pet_breeds` (`id_pet_breed`, `name`, `id_pet_type`) VALUES (DEFAULT, 'Pequeño', 2);
INSERT INTO `pgs`.`pet_breeds` (`id_pet_breed`, `name`, `id_pet_type`) VALUES (DEFAULT, 'Mediano', 2);
INSERT INTO `pgs`.`pet_breeds` (`id_pet_breed`, `name`, `id_pet_type`) VALUES (DEFAULT, 'Grande', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`pets`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`pets` (`id_pet`, `name`, `birth_date`, `gender`, `is_sterilized`, `is_vaccined`, `weight`, `photo`, `additional_observations`, `last_visited`, `id_user`, `id_pet_breed`, `id_fur_status`) VALUES (DEFAULT, 'Gary', STR_TO_DATE("December 15 2020", "%M %d %Y"), 1, 1, 1, 4.5, 'https://pets-static-img-pgs.s3.amazonaws.com/a1.jpeg', 'Parece un pancito', CURRENT_TIMESTAMP(), 1, 6, 1);
INSERT INTO `pgs`.`pets` (`id_pet`, `name`, `birth_date`, `gender`, `is_sterilized`, `is_vaccined`, `weight`, `photo`, `additional_observations`, `last_visited`, `id_user`, `id_pet_breed`, `id_fur_status`) VALUES (DEFAULT, 'Perrito bebé', STR_TO_DATE("August 10 2021", "%M %d %Y"), 1, 0, 0, 1, 'https://pets-static-img-pgs.s3.amazonaws.com/a2.jpeg', 'Está bien bebé', CURRENT_TIMESTAMP(), 1, 1, 1);
INSERT INTO `pgs`.`pets` (`id_pet`, `name`, `birth_date`, `gender`, `is_sterilized`, `is_vaccined`, `weight`, `photo`, `additional_observations`, `last_visited`, `id_user`, `id_pet_breed`, `id_fur_status`) VALUES (DEFAULT, 'Grace', STR_TO_DATE("January 27 2020", "%M %d %Y"), 2, 1, 1, 2.5, 'https://pets-static-img-pgs.s3.amazonaws.com/a3.jpeg', 'Es una gatica muy bonita', CURRENT_TIMESTAMP(), 1, 5, 1);
INSERT INTO `pgs`.`pets` (`id_pet`, `name`, `birth_date`, `gender`, `is_sterilized`, `is_vaccined`, `weight`, `photo`, `additional_observations`, `last_visited`, `id_user`, `id_pet_breed`, `id_fur_status`) VALUES (DEFAULT, 'Minnie', STR_TO_DATE("February 10 2022", "%M %d %Y"), 2, 0, 0, 2.5, 'https://pets-static-img-pgs.s3.amazonaws.com/a4.jpeg', 'Es cansona cuando la bañan', CURRENT_TIMESTAMP(), 1, 2, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`services`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`services` (`id_service`, `name`, `average_time`, `base_amount`) VALUES (DEFAULT, 'Baño', SEC_TO_TIME(3600), 25000);
INSERT INTO `pgs`.`services` (`id_service`, `name`, `average_time`, `base_amount`) VALUES (DEFAULT, 'Peluqueada', SEC_TO_TIME(1800), 15000);
INSERT INTO `pgs`.`services` (`id_service`, `name`, `average_time`, `base_amount`) VALUES (DEFAULT, 'Corte de uñas', SEC_TO_TIME(240), 4000);
INSERT INTO `pgs`.`services` (`id_service`, `name`, `average_time`, `base_amount`) VALUES (DEFAULT, 'Baño + Peluqueada', SEC_TO_TIME(5400), 40000);
INSERT INTO `pgs`.`services` (`id_service`, `name`, `average_time`, `base_amount`) VALUES (DEFAULT, 'Baño + Peluqueada + Corte Uñas', SEC_TO_TIME(5640), 44000);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`roles` (`id_role`, `name`) VALUES (DEFAULT, 'Admin');
INSERT INTO `pgs`.`roles` (`id_role`, `name`) VALUES (DEFAULT, 'Esteticista');
INSERT INTO `pgs`.`roles` (`id_role`, `name`) VALUES (DEFAULT, 'Dueño');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pgs`.`user_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `pgs`;
INSERT INTO `pgs`.`user_roles` (`id_user_role`, `id_user`, `id_role`) VALUES (DEFAULT, 1, 1);
INSERT INTO `pgs`.`user_roles` (`id_user_role`, `id_user`, `id_role`) VALUES (DEFAULT, 2, 2);
INSERT INTO `pgs`.`user_roles` (`id_user_role`, `id_user`, `id_role`) VALUES (DEFAULT, 3, 3);

COMMIT;

